#!/usr/bin/env python

import urllib2
import json
import time
import subprocess
import sys,os
import re

def usage():
    print "Usage: "+os.path.basename(__file__)+" [option] [CHANNEL_ID]"
    print "Baidu FM"
    print ""
    print "  -l, --list-channel          list all channels"
    print "  -h, --help                  display this help and exit"
    print ""
    print "Report bugs to <nabice@163.com>"
    sys.exit(1)
data = urllib2.urlopen("http://fm.baidu.com/dev/api/?tn=channellist&hashcode=f66347ccfc7746deb07188b739fa581f").read()
channelsdata = json.loads(data)
channels = channelsdata['channel_list']
channel_ids = []
if len(sys.argv) != 1:
    if sys.argv[1] == '-h' or sys.argv[1] == '--help':
        usage()
    if sys.argv[1] == '-l' or sys.argv[1] == '--list-channel':
        print "CHANNEL_ID                              CHANNEL_NAME" 
        for channel in channels:
            print "%-40s%s" % (channel['channel_id'],channel['channel_name'])
        sys.exit(0)
    for channel in channels:
        channel_ids.append(channel['channel_id'])
    if sys.argv[1] not in channel_ids:
        usage()
    else:
        channel_id = sys.argv[1]
else:
    channel_id = "public_yuzhong_huayu"
    
url = "http://fm.baidu.com/dev/api/?tn=playlist&id="+channel_id+"&special=flash&prepend=&format=json&_="+str(int(time.time()*1000))
songsdata = json.loads(urllib2.urlopen(url).read())
usevlc = subprocess.call("type rhythmbox",shell=True)
if usevlc:
    subprocess.call("sudo rm /tmp/baidufm.list",shell=True)
    baidufmlist = open("/tmp/baidufm.list", "w")
    for song in songsdata['list']:
        baidufmlist.write("http://127.0.0.1:8728/baiduflac.php?id="+str(song['id'])+"\n")
    subprocess.call("DISPLAY=:0 sudo vlc -f /tmp/baidufm.list --play-and-exit -I rc --rc-host=localhost:50022 -d",shell=True)
else:
    isplay = subprocess.call("rhythmbox-client --check-running",shell=True)
    if isplay:
        subprocess.call("rhythmbox-client",shell=True)
    for song in songsdata['list']:
        subprocess.call("rhythmbox-client --enqueue \"$(/home/nabice/src/baiduflac "+str(song['id'])+")\"",shell=True)
        if isplay:
            subprocess.call("rhythmbox-client --play",shell=True)
            isplay = 0
